### ISSUE TITLE
[Meta] Structure Overview

### ISSUE THREAD

**Issue by schickling** [learnapollo/learnapollo#1]
# Overview
- [ ] Brief Introduction
- [ ] Prerequisites

# Introduction
- [x] What is Apollo
- [x] Present the data model for the pokedex
- [x] Redux DevTools
- [x] Network Layer
- [x] Data normalization using dataIdFromObject

# Queries
- [x] Basic Queries
- [x] Advanced Queries
- [x] Data in Components
- [ ] Data Caching
- [ ] Static vs. Dynamic Queries
- [ ] skip/include
- [x] Variables
- [x] Using Fragments

# Mutations
- [x] Basic Mutations
- [x] Optimistic UI

# Advanced Topics
- [x] Pagination
- [ ] Polling vs. Subscriptions
- [ ] Query Batching
- [ ] fetchMore/updateQueries
- [ ] Preloading Data
- [ ] Testing with Jest

# Go further
- [ ] Wrap up

**Comment by tychota** [comment]
- Introduction:
  - Brief Introduction

> What value we add? What is the différence with relay? What problem it address ?
- Introduction:
  - What is apollo:

> It is really important to note that this will focus on using Apollo Client tools with react. Apollo have also the apollo servers and graphql-tools, and also have binding to angular. Thus the tutorial has to focus on a subpart of the tool

**Comment by schickling** [comment]
@tychota the plan is to split up the "code specific" part into different technologies (React, Angular, Swift...) by providing a switch. So a user could select "React" and would see Learn Apollo tailored to React + Apollo.

**Comment by tychota** [comment]
Oki ty for Info. I will Update my comment to  point out new idea for the intermediate part.

I will try to turn it in a way it address an issue that a a developper without apollo/graphql could have.

My idea so far are:
- no need to restructure the data taken to many endpoint to passs it down to the react component (the exemple feed with post and comment, which is down by facebook, is great)
- cached by default
- automatic loading state 
- automatic error state (while it can be improved by apollo and it certainly will, it so much better than having to setup ourself a redux global error state if call done with saga fails, by experience)
- optimistic result

**Comment by marktani** [comment]
I just added a fleshed out version of the structure. We should collect further topics that we want to cover.

A topic is checked if we have an exercise in #4 that covers it.
For every unchecked topic, we should either _add an exercise-oriented_ or _a concept-oriented_ section to the website.

**Comment by stubailo** [comment]
> Query batching

I think we should have a really clear idea of when this is and isn't valuable if we're going to cover it.

> Nested Queries

Is this just about using fields inside the queries? If we're covering query features separately I think it would be a good idea to also talk about static vs. dynamic queries, and how to use skip/include and variables to avoid manipulating query strings.

> fetchMore/updateQueries

Apollo 0.5 has a cleaner concept here called "query reducers", which actually let you use any redux action in the same way that updateQueries works. I don't think that will make the content very different, but something to keep an eye out for the coming days.

More advanced topics to consider:
1. Data normalization using dataIdFromObject
2. Cache redirection using https://github.com/apollostack/apollo-client/pull/809 (coming out in the next day or so)
3. Server side rendering

I think it would be useful to invite @tmeasday and @rdickert to take a look as well!

**Comment by marktani** [comment]
> Query batching

I agree. I moved it to "advanced".

> Nested Queries

Yes, this is about selecting scalar/non-scalar fields in queries. Good points!

I'll look through the advanced topics you suggested to consider. At the moment I see the advanced topics more as long-term, so I wouldn't prioritize them for now.

**Comment by marktani** [comment]
> Nested Queries

I renamed Nested Queries to Advanced Queries. This should include various query options, variables and more as suggested by @stubailo.

**Comment by marktani** [comment]
Closing this. For more discussion create a comment or new issue. :slightly_smiling_face:
