### ISSUE TITLE
[Meta] Progress Overview

### ISSUE THREAD

**Issue by marktani** [learnapollo/learnapollo#5]
# General

* [ ] proof-read (content/language) @stubailo @marktani 
* [ ] add switch between tutorial tracks @schickling #2
* [x] provide zip file after Git auth @schickling 
* [x] migrate to [new usage of fragments](https://github.com/apollostack/graphql-fragments#migrating)

# Tutorial Tracks

* React @marktani
  * [x] do all the exercises from start to finish
  * [x] 01 - start with plain react app, add apollo to solution
  * [ ] iterate on 06 - Multiple Mutations (updateQueries?)
  * [x] 07 - Pagination
  * [x] 01 - add error handling in render function
* Angular 2 @gsans @kamilkisiela 
   * [ ] finish first draft of app and texts
* React-Native @tychota 
   * [ ] finish first draft of app and texts

# Excursions

* [ ] Redux DevTools @tychota 
* [ ] Mutation Results and Optimistic UI @marktani
* [ ] Think of more excursions

**Comment by crapthings** [comment]
will there be an apollo server tutorial ?

**Comment by schickling** [comment]
Good point @crapthings. It's not planned at this point of time since Learn Apollo is targeted for frontend developers. We make it super easy by baking in a [GraphQL endpoint](https://graph.cool/) out of the box like in Learn Relay. 🎉
